import type { HistoricalDetection } from "@/hooks/use-audio-engine"
import {
  freqToNote,
  getFreqBandLabel,
  getRecGain,
  getRecQ,
} from "@/lib/audio-utils"

function formatTime(timestamp: number): string {
  const date = new Date(timestamp)
  return date.toLocaleTimeString("en-US", {
    hour12: true,
    hour: "numeric",
    minute: "2-digit",
    second: "2-digit",
  })
}

function pad(str: string, len: number): string {
  return str.padEnd(len)
}

export function exportSessionCsv(history: HistoricalDetection[]) {
  if (history.length === 0) return

  const sorted = [...history].sort((a, b) => a.frequency - b.frequency)
  const now = new Date()
  const lines: string[] = []

  lines.push("Frequency (Hz),Note,Band,Peak dB,Hit Count,First Seen,Last Seen,Rec Gain (dB),Rec Q,Severity")

  for (const det of sorted) {
    const note = freqToNote(det.frequency)
    const band = getFreqBandLabel(det.frequency)
    const gain = getRecGain(det.peakMagnitude)
    const q = getRecQ(det.peakMagnitude)
    const severity = det.peakMagnitude > -15 ? "CRITICAL" : det.peakMagnitude > -25 ? "HIGH" : "MODERATE"
    lines.push(
      `${det.frequency.toFixed(1)},${note},${band},${det.peakMagnitude.toFixed(1)},${det.hitCount},${formatTime(det.firstSeen)},${formatTime(det.lastSeen)},${gain},${q},${severity}`
    )
  }

  const content = lines.join("\n")
  const blob = new Blob([content], { type: "text/csv" })
  const url = URL.createObjectURL(blob)
  const link = document.createElement("a")
  link.href = url
  link.download = `KillTheRing_Session_${now.toISOString().slice(0, 10)}.csv`
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}

export function exportSessionLog(history: HistoricalDetection[]) {
  if (history.length === 0) return

  const sorted = [...history].sort((a, b) => a.frequency - b.frequency)
  const now = new Date()
  const dateStr = now.toLocaleDateString("en-US", {
    weekday: "short",
    year: "numeric",
    month: "short",
    day: "numeric",
  })
  const timeStr = now.toLocaleTimeString("en-US", {
    hour12: true,
    hour: "numeric",
    minute: "2-digit",
    second: "2-digit",
  })

  const divider = "=".repeat(72)
  const thinDiv = "-".repeat(72)
  const lines: string[] = []

  lines.push(divider)
  lines.push("  KillTheRing -- Session Report")
  lines.push(divider)
  lines.push("")
  lines.push(`  Date     : ${dateStr}`)
  lines.push(`  Time     : ${timeStr}`)
  lines.push(`  Events   : ${sorted.length}`)
  lines.push("")
  lines.push(thinDiv)
  lines.push(
    `  ${pad("Freq", 12)}${pad("Note", 6)}${pad("Band", 8)}${pad("Peak dB", 10)}${pad("Hits", 6)}${pad("First Seen", 14)}${pad("Last Seen", 14)}`
  )
  lines.push(thinDiv)

  for (const det of sorted) {
    const hz =
      det.frequency >= 1000
        ? `${(det.frequency / 1000).toFixed(2)} kHz`
        : `${Math.round(det.frequency)} Hz`
    const note = freqToNote(det.frequency)
    const band = getFreqBandLabel(det.frequency)
    const peak = `${det.peakMagnitude.toFixed(1)} dB`
    const hits = `${det.hitCount}x`
    const first = formatTime(det.firstSeen)
    const last = formatTime(det.lastSeen)

    lines.push(
      `  ${pad(hz, 12)}${pad(note, 6)}${pad(band, 8)}${pad(peak, 10)}${pad(hits, 6)}${pad(first, 14)}${pad(last, 14)}`
    )
  }

  lines.push(thinDiv)
  lines.push("")
  lines.push("  EQ Recommendations:")
  lines.push("")

  for (const det of sorted) {
    const hz =
      det.frequency >= 1000
        ? `${(det.frequency / 1000).toFixed(2)} kHz`
        : `${Math.round(det.frequency)} Hz`
    const gain = getRecGain(det.peakMagnitude)
    const q = getRecQ(det.peakMagnitude)
    const severity =
      det.peakMagnitude > -15 ? "CRITICAL" : det.peakMagnitude > -25 ? "HIGH" : "MODERATE"

    lines.push(`  [${severity}]  ${pad(hz, 12)}  Cut ${gain} dB   Q = ${q}`)
  }

  lines.push("")
  lines.push(divider)
  lines.push("  Generated by KillTheRing  |  killthering.com")
  lines.push(divider)
  lines.push("")

  const content = lines.join("\n")
  const blob = new Blob([content], { type: "text/plain" })
  const url = URL.createObjectURL(blob)
  const link = document.createElement("a")
  link.href = url
  link.download = `KillTheRing_Session_${now.toISOString().slice(0, 10)}.txt`
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}


